#!/bin/bash
set -e

echo "Starting API documentation build process..."

# Ensure Node.js is available
if ! command -v node &> /dev/null; then
    echo "Error: node is not installed. Install Node.js and try again."
    exit 1
fi

# Discover all openapi-*.json in website/static/specs/ and extract versions (descending)
SPECS=()
for f in website/static/specs/openapi-*.json; do
    [ -f "$f" ] || continue
    base="$(basename "$f")"
    base="${base#openapi-}"
    ver="${base%.json}"
    SPECS+=( "$ver" )
done
# Sort versions descending
IFS=$'\n' SPECS=($(printf '%s\n' "${SPECS[@]}" | sort -Vr)); unset IFS

if [ ${#SPECS[@]} -eq 0 ]; then
    echo "Error: No openapi-*.json files found in website/static/specs/."
    exit 1
fi

DEFAULT_VER="${SPECS[0]}"
echo "Discovered versions (desc): ${SPECS[*]} (default: $DEFAULT_VER)"

# 1. Generate website/src/api-versions.js (consumed by React components)
VERSIONS_JS="website/src/api-versions.js"
{
    echo "// Auto-generated by make.sh -- do not edit"
    printf "export const versions = ["
    first=1
    for v in "${SPECS[@]}"; do
        [ "$first" -eq 1 ] && first=0 || printf ","
        printf "'%s'" "$v"
    done
    printf "];\n"
    echo "export const defaultVersion = '${DEFAULT_VER}';"
} > "$VERSIONS_JS"
echo "Generated $VERSIONS_JS"

# 2. Build Docusaurus site
echo "Building Docusaurus site..."
cd website && npm install && npm run build
echo "Docusaurus build done."

echo "Build process completed! Output is in website/build/"
